const DATA_JP = {
  // ── 共用導覽列 ──────────────────────────────────────────────
  nav: {
    siteTitle: "MYFILE",
    links: {
      home: { label: "ホーム", href: "./index.html" },
      intro: { label: "自己紹介", href: "./intro.html" },
      works: { label: "作品", href: "./works.html" },
      contact: { label: "連絡先", href: "./contact.html" },
    },
  },

  // ── index.html ───────────────────────────────────────────────
  home: {
    title: "MYFILE",
    subtitle: "K.Y.W.",
  },

  // ── intro.html ───────────────────────────────────────────────
  intro: {
    pageTitle: "KYW",
    sections: [
      {
        heading: "経歴",
        type: "list",
        items: [
          {
            text: "新北市立板橋高級中学校",
          },
          {
            text: "国立台北教育大学",
            children: [
              {
                text: "芸術と造形デザイン学科",
              },
              {
                text: "デジタルテクノロジーデザイン学科",
              },
            ],
          },
        ],
      },
      {
        heading: "プロフィール",
        type: "paragraph",
        lines: [
          `先は国立台北教育大学芸術造形デザイン学科に在籍しておりましたが、
WebとデジタルデザインへのつよいきょうみからJavaScriptやReactを独学で学ぶようになり、
現在のデジタルテクノロジーデザイン学科へ転科いたしました。

現在もReactを用いた個人制作を通じて、フロントエンドとUIデザインの両面から
スキルアップを続けています。
制作では配色・余白・文字組みなど、細かい部分の積み重ねを大切にしており、
「見た目の雰囲気」と「使いやすさ」が自然につながるデザインを目指しています。

チームでの制作では、自分の意見をきちんと伝えながらも、
メンバーの考えをしっかり聞いて、より良い方向があればすぐに切り替えられるよう心がけています。
「自分の案にこだわるより、チームとして良いものを作ること」を大切にしています。

Webデザイナーとして、見た目だけでなく、
ユーザーが自然に使えるサイトを一緒に作っていきたいと考えています。`,
        ],
      },
    ],
    bottomVisual: {
      texts: ["", "災燼の末裔", "冥淵の龍"],
    },
  },

  // ── works.html ───────────────────────────────────────────────
  works: {
    pageTitle: "制作実績",
    projects: [
      {
        heading: "古林萃室",
        items: [
          {
            label: "ステータス",
            state: ["開発中", "#695e3f", "https://tea-shop-q3tn.vercel.app/"],
          },
          {
            label: "作品種別",
            value: "Webサイト",
            note: "React フレームワーク使用・Vercel にてデプロイ",
          },
          {
            label: "コンセプト",
            description: `深みのあるオリーブグリーンと柔らかなベージュ系カラーを基調とし、
ブランドコンセプトである「自然・静けさ・伝統」を感じられるデザインを目指しました。

背景にはグラデーションや全幅カルーセルを組み合わせ、
茶園の空気感や落ち着いた雰囲気が伝わるよう構成しています。

フォントは明朝体を中心に選定し、
見出し・本文・ナビゲーションで役割を分けることで、
情報の読みやすさとブランドイメージの両立を意識しました。

また、GSAP ScrollTriggerを用いたスクロールアニメーションにより、
コンテンツが自然な流れで表示されるよう設計し、
閲覧時にゆったりとしたリズムを感じられる体験を目指しています。

商品ページではフィルタリング機能と詳細表示機能を実装し、
情報量が多い中でも目的の商品へアクセスしやすいUI構成を意識しました。`,
          },
          // {
          //   label: "カラーパレット",
          //   palette: [
          //     {
          //       id: "For dark theme color (text, nav item hover background)",
          //       color: "#43453c",
          //     },
          //     {
          //       id: "For light theme color (text on dark, hover glow, background)",
          //       color: "#d0d9be",
          //     },
          //     {
          //       id: "For nav background / footer background",
          //       color: "#000000",
          //     },
          //     {
          //       id: "For content section background gradient (top)",
          //       color: "rgba(208, 217, 190, 0.9)",
          //     },
          //     {
          //       id: "For content section background gradient (mid)",
          //       color: "rgba(151, 128, 46, 0.9)",
          //     },
          //     {
          //       id: "For content section background gradient (bottom)",
          //       color: "rgba(106, 35, 0, 0.9)",
          //     },
          //   ],
          // },
          {
            label: "制作上の課題",
            list: [
              {
                text: `GSAPのアニメーションがReactの再レンダリング後に動かなくなった`,
                solution: `useEffect内でGSAPを初期化し、
                  gsapSetup.jsにプラグイン登録をまとめることでマウント後に一度だけ実行されるよう整理した
                  `,
                note: `Reactの「いつ何が起きるか」の流れをちゃんと理解していないと、
                ライブラリとの連携でハマることがわかった。
                エラーが出るたびに仕組みへの理解が深まった。`,
              },
              {
                text: `
                ブレークポイントによってナビゲーションバーとコンテンツが重なってしまった`,
                solution: `CSSカスタムプロパティ（--navHeight）でナビの高さを一元管理し、
                calc()でmargin-topを動的に算出。media queryで細かく調整した`,
                note: `「同じ値を何カ所にも書く」状態がバグの原因になると気づき、
                変数で一元管理する習慣が自然に身についた。`,
              },
            ],
          },
          {
            label: "更新履歴",
            link: {
              text: ["バージョン更新履歴", "デプロイ成果物"],
              href: [
                "https://github.com/noxHub1230/teaShop/commits/main/",
                "https://tea-shop-q3tn.vercel.app/",
              ],
            },
          },
          {
            label: "使用素材",
            links: [
              {
                text: "Home Page Background",
                href: "https://giphy.com/gifs/forest-TuptaxRZphuyA",
              },
              {
                text: "Other images are generated by ChatGPT.",
                href: "https://chatgpt.com",
              },
            ],
          },
        ],
      },
      {
        heading: "Toyhouse Profileテンプレート",
        items: [
          {
            label: "ステータス",
            state: ["完成", "#3f693f", "https://toyhou.se/Nokinok"],
          },
          {
            label: "作品種別",
            value: "Web（部分テンプレート）",
            note: "",
          },
          {
            label: "コンセプト",
            description: `オリジナルキャラクター「モナクシア」の世界観をもとに、
暗めの藍紫系カラーと淡い発光表現を組み合わせ、
落ち着きのある幻想的なデザインを目指しました。

背景には半透明レイヤーやアニメーション表現を取り入れ、
限られたテンプレート環境の中でも、
視覚的な没入感を感じられる構成を意識しています。

レイアウトにはBootstrapのグリッドシステムを活用し、
キャラクターイラストとプロフィール情報を整理して配置することで、
情報量が多い中でも閲覧しやすい構成となるよう調整しました。

また、タブ切り替えによって情報を分類し、
必要な内容へ直感的にアクセスできる導線設計を意識しています。

Toyhouse特有の制約がある環境下でも、
デザイン性と閲覧性の両立を目指して制作いたしました。。`,
          },
          // {
          //   label: "カラーパレット",
          //   palette: [
          //     { id: "For text shadow", color: "aqua" },
          //     {
          //       id: "For text color, text shadow(active), line",
          //       color: "#affcff",
          //     },
          //     {
          //       id: "For text shadow(hover), text color(active)",
          //       color: "#2f25fa",
          //     },
          //     {
          //       id: "For reder layer of left area",
          //       color: "rgba(8, 26, 107, 0.99)",
          //     },
          //     {
          //       id: "For reder layer of page background",
          //       color:
          //         "linear-gradient(90deg, rgb(28,28,37), rgb(32,22,82), rgba(32,22,82), rgb(35,33,92), rgba(31,50,121,0.8))",
          //     },
          //     {
          //       id: "For navigator background",
          //       color:
          //         "linear-gradient(180deg, rgb(29,21,67), rgb(32,22,82), rgba(32,22,82), rgb(35,33,92), rgba(31,50,121,0.8))",
          //     },
          //   ],
          // },
          {
            label: "制作上の課題",
            list: [
              {
                text: `Toyhouseのプラットフォーム上ではCSSの適用範囲が制限されており、
                プラットフォーム側のスタイルを上書きできない箇所があった`,
                solution: `inline styleの直接記述や、詳細度の高いセレクタを使って対応した`,
                note: `制約があるからこそ「どうすれば実現できるか」を深く考える習慣がついた。
                この経験を通じて、BootstrapとカスタムCSSを組み合わせる柔軟さも身についたと思う。`,
              },
            ],
          },
          {
            label: "更新履歴",
            link: {
              text: ["", "デプロイ成果物"],
              href: ["#", "https://toyhou.se/Nokinok"],
              note: "Toyhouse上のエディタにて開発を行ったため、バージョン履歴は一切保存されておりません",
            },
          },
          {
            label: "使用素材",
            links: [
              {
                text: "Background",
                href: "https://giphy.com/gifs/headlikeanorange-landscape-river-salmon-KH00JXnc2PQwE",
              },
              {
                text: "Profile Card Background",
                href: "https://giphy.com/gifs/water-wave-flow-X4fPTLm2TCtkNiJnhE",
              },
              {
                text: "Icons",
                href: "https://fontawesome.com/search?ic=free-collection",
              },
              {
                text: "Background Music",
                href: "https://www.youtube.com/watch?v=aHjpOzsQ9YI",
              },
            ],
          },
        ],
      },
      {
        heading: "MYFILE(旧版)",
        items: [
          {
            label: "ステータス",
            state: [
              "完成",
              "#3f693f",
              "https://unkn0321.github.io/2025WebPage2/",
            ],
          },
          {
            label: "作品種別",
            value: "Webサイト",
            note: "GitHub Pages",
          },
          {
            label: "コンセプト",
            description: `「静かだけど、記憶に残る」サイトを目指してデザインしました。

深みのある藍紫色をベースに、テキストに淡い発光表現を加えることで、
暗い背景の中でも読みやすく、全体に統一感のある雰囲気をつくっています。

背景動画の上に半透明レイヤーを重ねたのは、
セクションごとに印象がバラバラにならないようにするためです。
動画の動きを生かしつつ、コンテンツが主役になるバランスを意識しました。

フォントは見出し・本文・ナビゲーションで使い分け、
「どこを先に読めばいいか」が自然にわかる構成にしています。

ホバー時のアニメーションはあえて小さくシンプルにしました。
派手な動きより、触れたときにちょっと嬉しくなるような、
さりげない体験を大切にしたかったからです。`,
          },
          // {
          //   label: "カラーパレット",
          //   palette: [
          //     { id: "For text shadow", color: "aqua" },
          //     {
          //       id: "For text color, text shadow(active), line",
          //       color: "#affcff",
          //     },
          //     {
          //       id: "For text shadow(hover), text color(active)",
          //       color: "#2f25fa",
          //     },
          //     {
          //       id: "For reder layer of left area",
          //       color: "rgba(8, 26, 107, 0.99)",
          //     },
          //     {
          //       id: "For reder layer of page background",
          //       color:
          //         "linear-gradient(90deg, rgb(28,28,37), rgb(32,22,82), rgba(32,22,82), rgb(35,33,92), rgba(31,50,121,0.8))",
          //     },
          //     {
          //       id: "For navigator background",
          //       color:
          //         "linear-gradient(180deg, rgb(29,21,67), rgb(32,22,82), rgba(32,22,82), rgb(35,33,92), rgba(31,50,121,0.8))",
          //     },
          //   ],
          // },
          {
            label: "制作上の課題",
            list: [
              {
                text: "一部の機能の実装にJavaScriptが必要とわかった",
                solution: "参考資料を調べながら自力で実装方法を考え、解決し",
                note: `同じ処理でもJavaScriptに移すほうがCSSの記述量を減らせる場合があることを発見した。
                最初から「これはCSSで書く」と決めずに、柔軟に手段を選ぶことが大切だと感じた。`,
              },
            ],
          },
          {
            label: "更新履歴",
            link: {
              text: ["バージョン更新履歴", "デプロイ成果物"],
              href: [
                "https://github.com/unkn0321/2025WebPage2/commits/main/",
                "https://unkn0321.github.io/2025WebPage2/",
              ],
            },
          },
          {
            label: "使用素材",
            links: [
              {
                text: "Intro Page Background",
                href: "https://www.pexels.com/video/a-pastel-of-yellow-liquid-forms-different-patterns-3051357/",
              },
              {
                text: "Works Page Background",
                href: "https://www.pexels.com/video/abstract-video-4990242/",
              },
              {
                text: "Contact Page Background",
                href: "https://www.pexels.com/video/a-close-up-of-a-white-wave-pattern-4779866/",
              },
              {
                text: "left Area Background",
                href: "https://www.hcn.org/issues/54-9/climate-change-how-a-hidden-cave-can-help-scientists-understand-the-climate/",
              },
            ],
          },
        ],
      },
    ],
  },

  // ── contact.html ─────────────────────────────────────────────
  contact: {
    pageTitle: "連絡先",
    sections: [
      {
        heading: "SNS",
        type: "links",
        items: [
          {
            text: "Facebook",
            href: "https://www.facebook.com/gao.yu.wen.697831",
          },
        ],
      },
      {
        heading: "その他",
        type: "list",
        items: [
          { label: "携帯電話", value: "0905932786" },
          {
            label: "メールアドレス",
            value: `
            （国内連絡用アドレス）35fghu@gmail.com
              （海外連絡用アドレス）nokinok0321@gmail.com`,
          },
        ],
      },
    ],
  },
};
